// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "task-management/internal/entities"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/gofrs/uuid"
)

// Task is an autogenerated mock type for the Task type
type Task struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *Task) Create(ctx context.Context, _a1 *entities.Task) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Task) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Task) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, page, pageSize, status
func (_m *Task) GetAll(ctx context.Context, page int, pageSize int, status *entities.TaskStatus) ([]entities.Task, error) {
	ret := _m.Called(ctx, page, pageSize, status)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entities.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *entities.TaskStatus) ([]entities.Task, error)); ok {
		return rf(ctx, page, pageSize, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *entities.TaskStatus) []entities.Task); ok {
		r0 = rf(ctx, page, pageSize, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, *entities.TaskStatus) error); ok {
		r1 = rf(ctx, page, pageSize, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Task) GetByID(ctx context.Context, id uuid.UUID) (*entities.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *Task) Update(ctx context.Context, _a1 *entities.Task) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Task) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTask creates a new instance of Task. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTask(t interface {
	mock.TestingT
	Cleanup(func())
}) *Task {
	mock := &Task{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
